# ==============================================================
#  Downloads the three site fonts from Google into the repo, once.
#
#  Why: next/font currently fetches them from Google on every build.
#  When Google is unreachable from the runner, the build fails
#  (happened 2026-09-23). After this script the fonts live in the
#  repo and the build depends on nobody.
#
#  Run from the repo root:
#      powershell -ExecutionPolicy Bypass -File scripts\fetch-fonts.ps1
#
#  No Node required. ASCII only on purpose: Windows PowerShell 5.1
#  reads .ps1 as ANSI, and non-ASCII comments break the parser.
# ==============================================================

$ErrorActionPreference = 'Stop'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
$ProgressPreference = 'SilentlyContinue'   # Invoke-WebRequest is much faster without the progress bar

$root   = Split-Path -Parent $PSScriptRoot
$outDir = Join-Path $root 'public\fonts'
$cssOut = Join-Path $root 'src\styles\fonts.css'

New-Item -ItemType Directory -Force -Path $outDir | Out-Null
New-Item -ItemType Directory -Force -Path (Split-Path $cssOut) | Out-Null

# Chrome UA - without it Google serves legacy ttf instead of woff2
$UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'

# Exactly the weights used in src/lib/fonts.ts
$families = @(
  @{ slug = 'rubik';      query = 'Rubik:wght@500;600;700' },
  @{ slug = 'heebo';      query = 'Heebo:wght@400;500;700' },
  @{ slug = 'frank-ruhl'; query = 'Frank+Ruhl+Libre:wght@700' }
)
$wantedSubsets = @('hebrew', 'latin')

$faces = @()

foreach ($f in $families) {
  $url = "https://fonts.googleapis.com/css2?family=$($f.query)&display=swap"
  Write-Host ("CSS   {0,-12} ... " -f $f.slug) -NoNewline
  $css = (Invoke-WebRequest -Uri $url -UserAgent $UA -UseBasicParsing).Content
  Write-Host "ok"

  $pattern = '/\*\s*([a-z0-9\-]+)\s*\*/\s*@font-face\s*\{(.*?)\}'
  foreach ($m in [regex]::Matches($css, $pattern, 'Singleline')) {
    $subset = $m.Groups[1].Value
    if ($wantedSubsets -notcontains $subset) { continue }

    $body   = $m.Groups[2].Value
    $family = [regex]::Match($body, "font-family:\s*'([^']+)'").Groups[1].Value
    $weight = [regex]::Match($body, 'font-weight:\s*(\d+)').Groups[1].Value
    $src    = [regex]::Match($body, 'url\((https://[^)]+\.woff2)\)').Groups[1].Value
    $range  = [regex]::Match($body, 'unicode-range:\s*([^;]+);').Groups[1].Value.Trim()

    if (-not $src) { continue }

    $faces += [pscustomobject]@{
      family = $family
      weight = $weight
      subset = $subset
      url    = $src
      range  = $range
      file   = "$($f.slug)-$weight-$subset.woff2"
    }
  }
}

if ($faces.Count -eq 0) {
  throw 'No @font-face found. Either Google changed the CSS format, or there is no network.'
}

Write-Host ''
foreach ($face in $faces) {
  $dest = Join-Path $outDir $face.file
  Write-Host ("{0,-34} " -f $face.file) -NoNewline
  Invoke-WebRequest -Uri $face.url -OutFile $dest -UserAgent $UA -UseBasicParsing
  $kb = [math]::Round((Get-Item $dest).Length / 1KB)
  Write-Host "$kb KB"
}

# ---- generate the stylesheet --------------------------------
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('/*')
[void]$sb.AppendLine(' * Generated by scripts/fetch-fonts.ps1 - do not edit by hand.')
[void]$sb.AppendLine(' * Fonts are served from our own domain. No request to Google,')
[void]$sb.AppendLine(' * neither at build time nor at runtime.')
[void]$sb.AppendLine(' */')
[void]$sb.AppendLine('')

foreach ($face in $faces) {
  [void]$sb.AppendLine('@font-face {')
  [void]$sb.AppendLine("  font-family: '$($face.family)';")
  [void]$sb.AppendLine('  font-style: normal;')
  [void]$sb.AppendLine("  font-weight: $($face.weight);")
  [void]$sb.AppendLine('  font-display: swap;')
  [void]$sb.AppendLine("  src: url('/fonts/$($face.file)') format('woff2');")
  [void]$sb.AppendLine("  unicode-range: $($face.range);")
  [void]$sb.AppendLine('}')
  [void]$sb.AppendLine('')
}

[void]$sb.AppendLine(':root {')
[void]$sb.AppendLine("  --font-rubik: 'Rubik', system-ui, -apple-system, sans-serif;")
[void]$sb.AppendLine("  --font-heebo: 'Heebo', system-ui, -apple-system, sans-serif;")
[void]$sb.AppendLine("  --font-frank: 'Frank Ruhl Libre', Georgia, 'Times New Roman', serif;")
[void]$sb.AppendLine('}')

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[IO.File]::WriteAllText($cssOut, ($sb.ToString() -replace "`r`n", "`n"), $utf8NoBom)

Write-Host ''
Write-Host "$($faces.Count) files -> public\fonts\"
Write-Host 'stylesheet  -> src\styles\fonts.css'
Write-Host ''
Write-Host 'Done. Tell Claude it ran; he will wire up fonts.ts and the layout.'
